name: simple-workflow

on: push

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
    - name: Hello
      run: echo Hello
  anotherjob:
    runs-on: ubuntu-latest
    steps:
    - run: echo This is another job
